version: '2'
services:
  campaignmanagersql:
    container_name: campaignmanagersql
    build: .
    environment:
      - 'MYSQL_ROOT_PASSWORD=P@ssw0rd'
      - 'MYSQL_DATABASE=campaign_manager_db'
      - 'MYSQL_USER=SA'
      - 'MYSQL_PASSWORD=P@ssw0rd'
    hostname: 'adminhost'
    ports:
      - '3306:3306'
