# Use an official mysql image as a parent image
FROM mysql:latest

# Make port 3306 available to the world outside this container
EXPOSE 3306

# Define environment variables
ENV MYSQL_ROOT_PASSWORD "P@ssw0rd"
ENV MYSQL_DATABASE "campaign_manager_db"
ENV MYSQL_USER "SA"
ENV MYSQL_PASSWORD "P@ssw0rd"
