server:
  port: 8383

spring:
  profiles:
    active: local
  flyway:
    baseline-on-migrate: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/campaign_manager_db
    username: SA
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: connPool
      maximum-pool-size: 10
      idleTimeout: 30000
      connectionTimeout: 1000
      minimum-idle: 10
      connectionTestQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: validate